apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Slack Exception Handler
  description: Slack Exception Handler Plugin for Reekoh IoT Platform. Post error notifications on Slack
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Logger
  price: 0
  tags:
    - logger
    - exception-logger
    - slack

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      webhook:
        label: Slack Webhook URL
        type: String
        maxLength: 1000
        required: true
        help: Specify the Slack Webhook URL to use.
      channel:
        label: Slack Channel
        type: String
        maxLength: 1000
        required: true
        help: Specify the Slack Channel to post messages.
      username:
        label: Slack Username
        type: String
        maxLength: 1000
        required: false
        help: "(Optional) Specify the Username of a Slack user."